### ISSUE TITLE
I am getting the following error:

### ISSUE THREAD

**Issue by Hosam928** [snypelife/parkalot-auto-reserve#17]
Eek, something went terribly wrong! Please consider opening an issue at https://github.com/snypelife/parkalot-auto-reserve/issues with the following error:
TypeError: Cannot read property 'readFile' of undefined
    at /Users/guest/projects/personal/parkalot-auto-reserve/cli2.js:38:36
    at Object.<anonymous> (/Users/Guest/projects/personal/parkalot-auto-reserve/cli2.js:136:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by Hosam928** [comment]
It was just updating node.
